// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//IMPORTANTE ABAJO:
// el reference es un apaño para que TypeScript reconozca los tipos de Node.js y evitar errores de compilación relacionados con el entorno de ejecución.
//de no ponerlo da un error en process.env["DATABASE_URL"] porque TypeScript no reconoce process.env como un objeto válido sin los tipos de Node.js.
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
