export interface Game {
  id: number;
  slug: string;
  title: string;
  description_es: string;
  description_en: string;
  coverUrl: string;
  releaseYear: number;
  genres: string[];
  themes: string[];
  platforms: string[];
  gameModes: string[];
  perspectives: string[];
  keywords: string[];
  developers: string[];
  publishers: string[];
  searchCount: number;
  difficulty: number | null;
  pace: number | null;
  narrative: number | null;
  complexity: number | null;
  strategy: number | null;
  exploration: number | null;
  violence: number | null;
  horror: number | null;
  darkness: number | null;
  tension: number | null;
  humor: number | null;
  isolation: number | null;
}
